import { Injectable } from '@angular/core';
import { Thing } from '../model/thing';
import { Observable, of } from 'rxjs';

@Injectable({
    providedIn: 'root',
})
export class ThingService {
    get(): Observable<Thing[]> {
        return of([
            {
                id: '1',
                name: 'Thing 1',
                description: 'Description 1',
                imageUrl: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                tags: ['tag1', 'tag2'],
                type: 'type1',
                status: 'status1',
                ownerId: 'owner1',
                ownerName: 'Owner 1',
                ownerImageUrl: 'https://via.placeholder.com/50',
                isPublic: true,
                isFavorite: false,
                isArchived: false,
                isDeleted: false,
            },
            {
                id: '2',
                name: 'Thing 2',
                description: 'Description 2',
                imageUrl: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                tags: ['tag3', 'tag4'],
                type: 'type2',
                status: 'status2',
                ownerId: 'owner2',
                ownerName: 'Owner 2',
                ownerImageUrl: 'https://via.placeholder.com/50',
                isPublic: false,
                isFavorite: true,
                isArchived: false,
                isDeleted: false,
            },
            {
                id: '3',
                name: 'Thing 3',
                description: 'Description 3',
                imageUrl: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                tags: ['tag5', 'tag6'],
                type: 'type3',
                status: 'status3',
                ownerId: 'owner3',
                ownerName: 'Owner 3',
                ownerImageUrl: 'https://via.placeholder.com/50',
                isPublic: true,
                isFavorite: false,
                isArchived: true,
                isDeleted: false,
            },
            {
                id: '4',
                name: 'Thing 4',
                description: 'Description 4',
                imageUrl: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                tags: ['tag7', 'tag8'],
                type: 'type4',
                status: 'status4',
                ownerId: 'owner4',
                ownerName: 'Owner 4',
                ownerImageUrl: 'https://via.placeholder.com/50',
                isPublic: false,
                isFavorite: true,
                isArchived: false,
                isDeleted: true,
            },
            {
                id: '5',
                name: 'Thing 5',
                description: 'Description 5',
                imageUrl: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                tags: ['tag9', 'tag10'],
                type: 'type5',
                status: 'status5',
                ownerId: 'owner5',
                ownerName: 'Owner 5',
                ownerImageUrl: 'https://via.placeholder.com/50',
                isPublic: true,
                isFavorite: false,
                isArchived: false,
                isDeleted: false,
            },
            {
                id: '6',
                name: 'Thing 6',
                description: 'Description 6',
                imageUrl: 'https://via.placeholder.com/150',
                createdAt: new Date(),
                updatedAt: new Date(),
                tags: ['tag11', 'tag12'],
                type: 'type6',
                status: 'status6',
                ownerId: 'owner6',
                ownerName: 'Owner 6',
                ownerImageUrl: 'https://via.placeholder.com/50',
                isPublic: false,
                isFavorite: true,
                isArchived: false,
                isDeleted: false,
            },
        ]);
    }
}
